### PR TITLE
Make tests file have executable permissions

### PR DESCRIPTION
**Pull request by bartbes**
Hopefully fixes the error you're getting with CI.

### CODE REVIEW

**Comment by Yonaba** [comment]
Awesome. Thanks, @bartbes,

Actually, It works fine, as you can see [here](https://travis-ci.org/Yonaba/30logclasscommons/builds/46714558). Though, the tests fails with Lua 5.2, because setfenv ([line 121](https://github.com/bartbes/30logclasscommons/blob/master/tests/tests.lua#L121)) is deprecated.
Well, I can either updated the _.travis.yml_ to skip building for Lua 5.2.
Or are you willing to update Class-Commons tests specification to support Lua 5.2 ? In that case, you might need a replacement for _setfenv_... Maybe [this](http://github.com/davidm/lua-compat-env) might help.

**Comment by bartbes** [comment]
It probably makes sense to revise the tests in general and possibly move to a well-known (but small?) testing library. That said, I think setfenv isn't _strictly_ necessary in the current codebase.

**Comment by Yonaba** [comment]
Hmm, I see.
Concerning a possible test library, I am very used to [Telescope](https://github.com/norman/telescope). It is really fine, and light enough, to me. There's also [busted](https://github.com/Olivine-Labs/busted), which has much more features, and also easy to use. But I'd go with Telescope. I can rewrite Class-Commons codebase with Telescope and send a PR.
Maybe this should be discussed in a separate issue on Class-Commons repository itself, since it will affect everyone using Class-Commons (I mean @kikito's MiddleClass, @vrld's Hump.class and Slither).

**Comment by bartbes** [comment]
Class Commons Tests repo ticket opened: https://github.com/bartbes/Class-Commons-Tests/issues/2

**Pull request merged**
